// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: cluster.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoteMessage_Kind int32

const (
	RemoteMessage_KIND_UNKNOWN               RemoteMessage_Kind = 0
	RemoteMessage_KIND_RPC                   RemoteMessage_Kind = 1
	RemoteMessage_KIND_NOTIFY                RemoteMessage_Kind = 2
	RemoteMessage_KIND_PUSH                  RemoteMessage_Kind = 3
	RemoteMessage_KIND_ON_SESSION_BIND_UID   RemoteMessage_Kind = 4
	RemoteMessage_KIND_ON_SESSION_CONNECT    RemoteMessage_Kind = 5
	RemoteMessage_KIND_ON_SESSION_DISCONNECT RemoteMessage_Kind = 6
)

// Enum value maps for RemoteMessage_Kind.
var (
	RemoteMessage_Kind_name = map[int32]string{
		0: "KIND_UNKNOWN",
		1: "KIND_RPC",
		2: "KIND_NOTIFY",
		3: "KIND_PUSH",
		4: "KIND_ON_SESSION_BIND_UID",
		5: "KIND_ON_SESSION_CONNECT",
		6: "KIND_ON_SESSION_DISCONNECT",
	}
	RemoteMessage_Kind_value = map[string]int32{
		"KIND_UNKNOWN":               0,
		"KIND_RPC":                   1,
		"KIND_NOTIFY":                2,
		"KIND_PUSH":                  3,
		"KIND_ON_SESSION_BIND_UID":   4,
		"KIND_ON_SESSION_CONNECT":    5,
		"KIND_ON_SESSION_DISCONNECT": 6,
	}
)

func (x RemoteMessage_Kind) Enum() *RemoteMessage_Kind {
	p := new(RemoteMessage_Kind)
	*p = x
	return p
}

func (x RemoteMessage_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoteMessage_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cluster_proto_enumTypes[0].Descriptor()
}

func (RemoteMessage_Kind) Type() protoreflect.EnumType {
	return &file_cluster_proto_enumTypes[0]
}

func (x RemoteMessage_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoteMessage_Kind.Descriptor instead.
func (RemoteMessage_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{19, 0}
}

type ServiceInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=Service_name,json=ServiceName,proto3" json:"Service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=Instance_id,json=InstanceId,proto3" json:"Instance_id,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	Frontend      bool                   `protobuf:"varint,4,opt,name=Frontend,proto3" json:"Frontend,omitempty"`
	Messages      map[string]int32       `protobuf:"bytes,5,rep,name=Messages,proto3" json:"Messages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInstance) Reset() {
	*x = ServiceInstance{}
	mi := &file_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInstance) ProtoMessage() {}

func (x *ServiceInstance) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInstance.ProtoReflect.Descriptor instead.
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInstance) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInstance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ServiceInstance) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ServiceInstance) GetFrontend() bool {
	if x != nil {
		return x.Frontend
	}
	return false
}

func (x *ServiceInstance) GetMessages() map[string]int32 {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     *ServiceInstance       `protobuf:"bytes,1,opt,name=Instances,proto3" json:"Instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetInstances() *ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{2}
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     *ServiceInstance       `protobuf:"bytes,1,opt,name=Instances,proto3" json:"Instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterRequest) GetInstances() *ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{4}
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=Service_name,json=ServiceName,proto3" json:"Service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoveryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*ServiceInstance     `protobuf:"bytes,1,rep,name=Instances,proto3" json:"Instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoveryResponse) GetInstances() []*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     *ServiceInstance       `protobuf:"bytes,1,opt,name=Instances,proto3" json:"Instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetInstances() *ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{8}
}

type NewMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     *ServiceInstance       `protobuf:"bytes,1,opt,name=Instances,proto3" json:"Instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMembersRequest) Reset() {
	*x = NewMembersRequest{}
	mi := &file_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMembersRequest) ProtoMessage() {}

func (x *NewMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMembersRequest.ProtoReflect.Descriptor instead.
func (*NewMembersRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *NewMembersRequest) GetInstances() *ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type NewMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewMembersResponse) Reset() {
	*x = NewMembersResponse{}
	mi := &file_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewMembersResponse) ProtoMessage() {}

func (x *NewMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewMembersResponse.ProtoReflect.Descriptor instead.
func (*NewMembersResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{10}
}

type DelMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=Service_name,json=ServiceName,proto3" json:"Service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=Instance_id,json=InstanceId,proto3" json:"Instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelMembersRequest) Reset() {
	*x = DelMembersRequest{}
	mi := &file_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMembersRequest) ProtoMessage() {}

func (x *DelMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMembersRequest.ProtoReflect.Descriptor instead.
func (*DelMembersRequest) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *DelMembersRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DelMembersRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DelMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=Service_name,json=ServiceName,proto3" json:"Service_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=Instance_id,json=InstanceId,proto3" json:"Instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelMembersResponse) Reset() {
	*x = DelMembersResponse{}
	mi := &file_cluster_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelMembersResponse) ProtoMessage() {}

func (x *DelMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelMembersResponse.ProtoReflect.Descriptor instead.
func (*DelMembersResponse) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{12}
}

func (x *DelMembersResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *DelMembersResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type RPCMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Route         string                 `protobuf:"bytes,4,opt,name=Route,proto3" json:"Route,omitempty"` // User/C2SLogin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCMessage) Reset() {
	*x = RPCMessage{}
	mi := &file_cluster_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCMessage) ProtoMessage() {}

func (x *RPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCMessage.ProtoReflect.Descriptor instead.
func (*RPCMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{13}
}

func (x *RPCMessage) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *RPCMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *RPCMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RPCMessage) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type NotifyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=Route,proto3" json:"Route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyMessage) Reset() {
	*x = NotifyMessage{}
	mi := &file_cluster_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyMessage) ProtoMessage() {}

func (x *NotifyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyMessage.ProtoReflect.Descriptor instead.
func (*NotifyMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyMessage) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *NotifyMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NotifyMessage) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_cluster_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{15}
}

func (x *PushMessage) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *PushMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OnSessionBindUIDMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     int64                  `protobuf:"varint,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	UID           int64                  `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnSessionBindUIDMessage) Reset() {
	*x = OnSessionBindUIDMessage{}
	mi := &file_cluster_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSessionBindUIDMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSessionBindUIDMessage) ProtoMessage() {}

func (x *OnSessionBindUIDMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSessionBindUIDMessage.ProtoReflect.Descriptor instead.
func (*OnSessionBindUIDMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{16}
}

func (x *OnSessionBindUIDMessage) GetSessionID() int64 {
	if x != nil {
		return x.SessionID
	}
	return 0
}

func (x *OnSessionBindUIDMessage) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type OnSessionConnectMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UID           int64                       `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Instances     map[string]*ServiceInstance `protobuf:"bytes,2,rep,name=Instances,proto3" json:"Instances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnSessionConnectMessage) Reset() {
	*x = OnSessionConnectMessage{}
	mi := &file_cluster_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSessionConnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSessionConnectMessage) ProtoMessage() {}

func (x *OnSessionConnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSessionConnectMessage.ProtoReflect.Descriptor instead.
func (*OnSessionConnectMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{17}
}

func (x *OnSessionConnectMessage) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *OnSessionConnectMessage) GetInstances() map[string]*ServiceInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type OnSessionDisconnectionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UID           int64                  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnSessionDisconnectionMessage) Reset() {
	*x = OnSessionDisconnectionMessage{}
	mi := &file_cluster_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnSessionDisconnectionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnSessionDisconnectionMessage) ProtoMessage() {}

func (x *OnSessionDisconnectionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnSessionDisconnectionMessage.ProtoReflect.Descriptor instead.
func (*OnSessionDisconnectionMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{18}
}

func (x *OnSessionDisconnectionMessage) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

type RemoteMessage struct {
	state                         protoimpl.MessageState         `protogen:"open.v1"`
	Kind                          RemoteMessage_Kind             `protobuf:"varint,1,opt,name=kind,proto3,enum=protos.RemoteMessage_Kind" json:"kind,omitempty"`
	RPCMessage                    *RPCMessage                    `protobuf:"bytes,2,opt,name=RPCMessage,proto3" json:"RPCMessage,omitempty"`
	NotifyMessage                 *NotifyMessage                 `protobuf:"bytes,3,opt,name=NotifyMessage,proto3" json:"NotifyMessage,omitempty"`
	PushMessage                   *PushMessage                   `protobuf:"bytes,4,opt,name=PushMessage,proto3" json:"PushMessage,omitempty"`
	OnSessionBindUIDMessage       *OnSessionBindUIDMessage       `protobuf:"bytes,5,opt,name=OnSessionBindUIDMessage,proto3" json:"OnSessionBindUIDMessage,omitempty"`
	OnSessionConnectMessage       *OnSessionConnectMessage       `protobuf:"bytes,6,opt,name=OnSessionConnectMessage,proto3" json:"OnSessionConnectMessage,omitempty"`
	OnSessionDisconnectionMessage *OnSessionDisconnectionMessage `protobuf:"bytes,7,opt,name=OnSessionDisconnectionMessage,proto3" json:"OnSessionDisconnectionMessage,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *RemoteMessage) Reset() {
	*x = RemoteMessage{}
	mi := &file_cluster_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteMessage) ProtoMessage() {}

func (x *RemoteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteMessage.ProtoReflect.Descriptor instead.
func (*RemoteMessage) Descriptor() ([]byte, []int) {
	return file_cluster_proto_rawDescGZIP(), []int{19}
}

func (x *RemoteMessage) GetKind() RemoteMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return RemoteMessage_KIND_UNKNOWN
}

func (x *RemoteMessage) GetRPCMessage() *RPCMessage {
	if x != nil {
		return x.RPCMessage
	}
	return nil
}

func (x *RemoteMessage) GetNotifyMessage() *NotifyMessage {
	if x != nil {
		return x.NotifyMessage
	}
	return nil
}

func (x *RemoteMessage) GetPushMessage() *PushMessage {
	if x != nil {
		return x.PushMessage
	}
	return nil
}

func (x *RemoteMessage) GetOnSessionBindUIDMessage() *OnSessionBindUIDMessage {
	if x != nil {
		return x.OnSessionBindUIDMessage
	}
	return nil
}

func (x *RemoteMessage) GetOnSessionConnectMessage() *OnSessionConnectMessage {
	if x != nil {
		return x.OnSessionConnectMessage
	}
	return nil
}

func (x *RemoteMessage) GetOnSessionDisconnectionMessage() *OnSessionDisconnectionMessage {
	if x != nil {
		return x.OnSessionDisconnectionMessage
	}
	return nil
}

var File_cluster_proto protoreflect.FileDescriptor

const file_cluster_proto_rawDesc = "" +
	"\n" +
	"\rcluster.proto\x12\x06protos\"\x85\x02\n" +
	"\x0fServiceInstance\x12!\n" +
	"\fService_name\x18\x01 \x01(\tR\vServiceName\x12\x1f\n" +
	"\vInstance_id\x18\x02 \x01(\tR\n" +
	"InstanceId\x12\x12\n" +
	"\x04Addr\x18\x03 \x01(\tR\x04Addr\x12\x1a\n" +
	"\bFrontend\x18\x04 \x01(\bR\bFrontend\x12A\n" +
	"\bMessages\x18\x05 \x03(\v2%.protos.ServiceInstance.MessagesEntryR\bMessages\x1a;\n" +
	"\rMessagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"H\n" +
	"\x0fRegisterRequest\x125\n" +
	"\tInstances\x18\x01 \x01(\v2\x17.protos.ServiceInstanceR\tInstances\"\x12\n" +
	"\x10RegisterResponse\"J\n" +
	"\x11DeregisterRequest\x125\n" +
	"\tInstances\x18\x01 \x01(\v2\x17.protos.ServiceInstanceR\tInstances\"\x14\n" +
	"\x12DeregisterResponse\"5\n" +
	"\x10DiscoveryRequest\x12!\n" +
	"\fService_name\x18\x01 \x01(\tR\vServiceName\"J\n" +
	"\x11DiscoveryResponse\x125\n" +
	"\tInstances\x18\x01 \x03(\v2\x17.protos.ServiceInstanceR\tInstances\"I\n" +
	"\x10HeartbeatRequest\x125\n" +
	"\tInstances\x18\x01 \x01(\v2\x17.protos.ServiceInstanceR\tInstances\"\x13\n" +
	"\x11HeartbeatResponse\"J\n" +
	"\x11NewMembersRequest\x125\n" +
	"\tInstances\x18\x01 \x01(\v2\x17.protos.ServiceInstanceR\tInstances\"\x14\n" +
	"\x12NewMembersResponse\"W\n" +
	"\x11DelMembersRequest\x12!\n" +
	"\fService_name\x18\x01 \x01(\tR\vServiceName\x12\x1f\n" +
	"\vInstance_id\x18\x02 \x01(\tR\n" +
	"InstanceId\"X\n" +
	"\x12DelMembersResponse\x12!\n" +
	"\fService_name\x18\x01 \x01(\tR\vServiceName\x12\x1f\n" +
	"\vInstance_id\x18\x02 \x01(\tR\n" +
	"InstanceId\"f\n" +
	"\n" +
	"RPCMessage\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x10\n" +
	"\x03Seq\x18\x02 \x01(\x03R\x03Seq\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x14\n" +
	"\x05Route\x18\x04 \x01(\tR\x05Route\"W\n" +
	"\rNotifyMessage\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\x12\x14\n" +
	"\x05Route\x18\x03 \x01(\tR\x05Route\"?\n" +
	"\vPushMessage\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"I\n" +
	"\x17OnSessionBindUIDMessage\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\x03R\tSessionID\x12\x10\n" +
	"\x03UID\x18\x02 \x01(\x03R\x03UID\"\xd0\x01\n" +
	"\x17OnSessionConnectMessage\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x03R\x03UID\x12L\n" +
	"\tInstances\x18\x02 \x03(\v2..protos.OnSessionConnectMessage.InstancesEntryR\tInstances\x1aU\n" +
	"\x0eInstancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.protos.ServiceInstanceR\x05value:\x028\x01\"1\n" +
	"\x1dOnSessionDisconnectionMessage\x12\x10\n" +
	"\x03UID\x18\x01 \x01(\x03R\x03UID\"\xae\x05\n" +
	"\rRemoteMessage\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.protos.RemoteMessage.KindR\x04kind\x122\n" +
	"\n" +
	"RPCMessage\x18\x02 \x01(\v2\x12.protos.RPCMessageR\n" +
	"RPCMessage\x12;\n" +
	"\rNotifyMessage\x18\x03 \x01(\v2\x15.protos.NotifyMessageR\rNotifyMessage\x125\n" +
	"\vPushMessage\x18\x04 \x01(\v2\x13.protos.PushMessageR\vPushMessage\x12Y\n" +
	"\x17OnSessionBindUIDMessage\x18\x05 \x01(\v2\x1f.protos.OnSessionBindUIDMessageR\x17OnSessionBindUIDMessage\x12Y\n" +
	"\x17OnSessionConnectMessage\x18\x06 \x01(\v2\x1f.protos.OnSessionConnectMessageR\x17OnSessionConnectMessage\x12k\n" +
	"\x1dOnSessionDisconnectionMessage\x18\a \x01(\v2%.protos.OnSessionDisconnectionMessageR\x1dOnSessionDisconnectionMessage\"\xa1\x01\n" +
	"\x04Kind\x12\x10\n" +
	"\fKIND_UNKNOWN\x10\x00\x12\f\n" +
	"\bKIND_RPC\x10\x01\x12\x0f\n" +
	"\vKIND_NOTIFY\x10\x02\x12\r\n" +
	"\tKIND_PUSH\x10\x03\x12\x1c\n" +
	"\x18KIND_ON_SESSION_BIND_UID\x10\x04\x12\x1b\n" +
	"\x17KIND_ON_SESSION_CONNECT\x10\x05\x12\x1e\n" +
	"\x1aKIND_ON_SESSION_DISCONNECT\x10\x062\x97\x02\n" +
	"\x0eRegistryServer\x12=\n" +
	"\bRegister\x12\x17.protos.RegisterRequest\x1a\x18.protos.RegisterResponse\x12C\n" +
	"\n" +
	"Deregister\x12\x19.protos.DeregisterRequest\x1a\x1a.protos.DeregisterResponse\x12?\n" +
	"\bDiscover\x12\x18.protos.DiscoveryRequest\x1a\x19.protos.DiscoveryResponse\x12@\n" +
	"\tHeartbeat\x12\x18.protos.HeartbeatRequest\x1a\x19.protos.HeartbeatResponse2\x99\x01\n" +
	"\rMembersServer\x12C\n" +
	"\n" +
	"NewMembers\x12\x19.protos.NewMembersRequest\x1a\x1a.protos.NewMembersResponse\x12C\n" +
	"\n" +
	"DelMembers\x12\x19.protos.DelMembersRequest\x1a\x1a.protos.DelMembersResponse2I\n" +
	"\fRemoteServer\x129\n" +
	"\aReceive\x12\x15.protos.RemoteMessage\x1a\x15.protos.RemoteMessage(\x01B\tZ\a/protosb\x06proto3"

var (
	file_cluster_proto_rawDescOnce sync.Once
	file_cluster_proto_rawDescData []byte
)

func file_cluster_proto_rawDescGZIP() []byte {
	file_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)))
	})
	return file_cluster_proto_rawDescData
}

var file_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_cluster_proto_goTypes = []any{
	(RemoteMessage_Kind)(0),               // 0: protos.RemoteMessage.Kind
	(*ServiceInstance)(nil),               // 1: protos.ServiceInstance
	(*RegisterRequest)(nil),               // 2: protos.RegisterRequest
	(*RegisterResponse)(nil),              // 3: protos.RegisterResponse
	(*DeregisterRequest)(nil),             // 4: protos.DeregisterRequest
	(*DeregisterResponse)(nil),            // 5: protos.DeregisterResponse
	(*DiscoveryRequest)(nil),              // 6: protos.DiscoveryRequest
	(*DiscoveryResponse)(nil),             // 7: protos.DiscoveryResponse
	(*HeartbeatRequest)(nil),              // 8: protos.HeartbeatRequest
	(*HeartbeatResponse)(nil),             // 9: protos.HeartbeatResponse
	(*NewMembersRequest)(nil),             // 10: protos.NewMembersRequest
	(*NewMembersResponse)(nil),            // 11: protos.NewMembersResponse
	(*DelMembersRequest)(nil),             // 12: protos.DelMembersRequest
	(*DelMembersResponse)(nil),            // 13: protos.DelMembersResponse
	(*RPCMessage)(nil),                    // 14: protos.RPCMessage
	(*NotifyMessage)(nil),                 // 15: protos.NotifyMessage
	(*PushMessage)(nil),                   // 16: protos.PushMessage
	(*OnSessionBindUIDMessage)(nil),       // 17: protos.OnSessionBindUIDMessage
	(*OnSessionConnectMessage)(nil),       // 18: protos.OnSessionConnectMessage
	(*OnSessionDisconnectionMessage)(nil), // 19: protos.OnSessionDisconnectionMessage
	(*RemoteMessage)(nil),                 // 20: protos.RemoteMessage
	nil,                                   // 21: protos.ServiceInstance.MessagesEntry
	nil,                                   // 22: protos.OnSessionConnectMessage.InstancesEntry
}
var file_cluster_proto_depIdxs = []int32{
	21, // 0: protos.ServiceInstance.Messages:type_name -> protos.ServiceInstance.MessagesEntry
	1,  // 1: protos.RegisterRequest.Instances:type_name -> protos.ServiceInstance
	1,  // 2: protos.DeregisterRequest.Instances:type_name -> protos.ServiceInstance
	1,  // 3: protos.DiscoveryResponse.Instances:type_name -> protos.ServiceInstance
	1,  // 4: protos.HeartbeatRequest.Instances:type_name -> protos.ServiceInstance
	1,  // 5: protos.NewMembersRequest.Instances:type_name -> protos.ServiceInstance
	22, // 6: protos.OnSessionConnectMessage.Instances:type_name -> protos.OnSessionConnectMessage.InstancesEntry
	0,  // 7: protos.RemoteMessage.kind:type_name -> protos.RemoteMessage.Kind
	14, // 8: protos.RemoteMessage.RPCMessage:type_name -> protos.RPCMessage
	15, // 9: protos.RemoteMessage.NotifyMessage:type_name -> protos.NotifyMessage
	16, // 10: protos.RemoteMessage.PushMessage:type_name -> protos.PushMessage
	17, // 11: protos.RemoteMessage.OnSessionBindUIDMessage:type_name -> protos.OnSessionBindUIDMessage
	18, // 12: protos.RemoteMessage.OnSessionConnectMessage:type_name -> protos.OnSessionConnectMessage
	19, // 13: protos.RemoteMessage.OnSessionDisconnectionMessage:type_name -> protos.OnSessionDisconnectionMessage
	1,  // 14: protos.OnSessionConnectMessage.InstancesEntry.value:type_name -> protos.ServiceInstance
	2,  // 15: protos.RegistryServer.Register:input_type -> protos.RegisterRequest
	4,  // 16: protos.RegistryServer.Deregister:input_type -> protos.DeregisterRequest
	6,  // 17: protos.RegistryServer.Discover:input_type -> protos.DiscoveryRequest
	8,  // 18: protos.RegistryServer.Heartbeat:input_type -> protos.HeartbeatRequest
	10, // 19: protos.MembersServer.NewMembers:input_type -> protos.NewMembersRequest
	12, // 20: protos.MembersServer.DelMembers:input_type -> protos.DelMembersRequest
	20, // 21: protos.RemoteServer.Receive:input_type -> protos.RemoteMessage
	3,  // 22: protos.RegistryServer.Register:output_type -> protos.RegisterResponse
	5,  // 23: protos.RegistryServer.Deregister:output_type -> protos.DeregisterResponse
	7,  // 24: protos.RegistryServer.Discover:output_type -> protos.DiscoveryResponse
	9,  // 25: protos.RegistryServer.Heartbeat:output_type -> protos.HeartbeatResponse
	11, // 26: protos.MembersServer.NewMembers:output_type -> protos.NewMembersResponse
	13, // 27: protos.MembersServer.DelMembers:output_type -> protos.DelMembersResponse
	20, // 28: protos.RemoteServer.Receive:output_type -> protos.RemoteMessage
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_cluster_proto_init() }
func file_cluster_proto_init() {
	if File_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_proto_rawDesc), len(file_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_proto_depIdxs,
		EnumInfos:         file_cluster_proto_enumTypes,
		MessageInfos:      file_cluster_proto_msgTypes,
	}.Build()
	File_cluster_proto = out.File
	file_cluster_proto_goTypes = nil
	file_cluster_proto_depIdxs = nil
}
